export const WinterCloth = [
    {
      id: 1,
      image: require('../assets/scarf1.jpg'),
      title: 'Scarf',
      price:'1320',
      rating:4.5,
      description:"100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
      prices: [
        {size: 'S', price: '1.38', currency: '$'},
        {size: 'M', price: '3.15', currency: '$'},
        {size: 'L', price: '4.29', currency: '$'},
      ],
    },
    {
      id: 2,
      image: require('../assets/black_hoodie_mockup.jpg'),
      title: 'Black Jacket',
      price:'1320',
      rating:4.5,
      description:"100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
      prices: [
        {size: 'S', price: '1.38', currency: '$'},
        {size: 'M', price: '3.15', currency: '$'},
        {size: 'L', price: '4.29', currency: '$'},
      ],
    },
    {
      id: 3,
      image: require('../assets/green-front-sweater.jpg'),
      title: 'Sweater',
      price:'1320',
      rating:4.5,
      description:"100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
      prices: [
        {size: 'S', price: '1.38', currency: '$'},
        {size: 'M', price: '3.15', currency: '$'},
        {size: 'L', price: '4.29', currency: '$'},
      ],
    },
    {
        id: 4,
        image: require('../assets/34563.jpg'),
        title: 'Hoodie',
        price:'1320',
        rating:4.5,
        description:"100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
        prices: [
          {size: 'S', price: '1.38', currency: '$'},
          {size: 'M', price: '3.15', currency: '$'},
          {size: 'L', price: '4.29', currency: '$'},
        ],
      },
      {
        id: 5,
        image: require('../assets/40166.jpg'),
        title: 'Combo Hoodiee',
        price:'1320',
        rating:4.5,
        description:"100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
        prices: [
          {size: 'S', price: '1.38', currency: '$'},
          {size: 'M', price: '3.15', currency: '$'},
          {size: 'L', price: '4.29', currency: '$'},
        ],
      },
  ];